### ISSUE TITLE
[BUG] - Changes made with preset does not change preset to custom type with new changes

### ISSUE THREAD

**Issue by ZombieHDGaming** [FiniteSingularity/obs-noise#6]
**Describe the bug**
When using a base preset in the plugin, if any changes are made, the preset defaults + changes are not addressed to the custom preset, leading to issues when leaving the properties window. The preset will automatically reapply when re-entering the properties window and making a single edit. This can be seen for both just editing the source and after restarting OBS Studio and editing the source then.

**Without Restart**
1. Create noise source and select a preset.
2. Make changes to preset properties and save the source.
3. Re-enter the properties window and notice settings have been changed to the preset.
4. Make a change and watch it reset to the default preset properties.

**With Restart**
1. Create noise source and select a preset.
2. Make changes to preset properties and save the source.
3. Close OBS and reopen to the source properties.
4. See preset defaults applied without any rendered changes.
5. Make a change and watch it reset to the default preset properties.

**Expected behavior**
Preset properties changes should apply to the custom preset to not have such an issue occur because of the properties window overwriting with default preset properties.

**Environment**
 - OS/Version:  Windows 10
 - OBS Version: 30.0.2
 - Noise Plugin Version: 0.0.3 Alpha (with latest PR changes)

**GPU**
 - GPU make/model: RTX 3060
 - GPU VRAM 12GB

**Comment by FiniteSingularity** [comment]
Got a fix for this incoming.  Will be in a PR soon.
